version: '3.8'

services:  
  web:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile
    image: publicazo_img
    container_name: publicazo 
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:setup && bundle exec rails s -p 5003 -b '0.0.0.0'"
    volumes: 
      - .:/com.docker.devenvironments.code
    ports:
      - "5003:5003"
    